//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACRemasteredLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACRemasteredLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Player]
        ///LastUsedProfile=1664795198
        ///[Startup]
        ///StickyKeys=2
        ///ToggleKeys=2
        ///FilterKeys=2
        ///[Graphics]
        ///DisplayWidth=1920
        ///DisplayHeight=1080
        ///RefreshRate=85
        ///ShadowDistance=4
        ///ShadowMapSize=1024
        ///SkipMips=0
        ///Multisampling=2
        ///DistanceLOD=1
        ///MaxNPCLODLevel=5
        ///SmallObjectsCullDistanceModifier=1
        ///MediumObjectsCullDistanceModifier=1
        ///MaxSearchTimePerFrame=10000
        ///VSynch=1
        ///Fullscreen=1
        ///PostFX=1
        ///Particle=1
        ///LODBlend=1
        ///Clutter=1
        ///Layers=1
        ///Anisotropic=1
        ///AlphaTest=1
        ///DistanceLODEnabled=0
        ///ProcessBoneModifiers=1        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Assassin {
            get {
                return ResourceManager.GetString("Assassin", resourceCulture);
            }
        }
    }
}
